# Generated by Django 5.2.11 on 2026-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genericstringtaggeditem",
            name="object_id",
            field=models.CharField(
                db_index=True, max_length=150, verbose_name="Object id"
            ),
        ),
    ]
