# Generated by Django 5.2 on 2025-04-09 13:17

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0005_alter_dmp_project_alter_project_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "technologies",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("related", models.ManyToManyField(blank=True, to="services.service")),
            ],
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("title", models.CharField(null=True)),
                ("description", models.TextField(null=True)),
                ("uri", models.CharField()),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("public", "Public available"),
                            ("private", "Available only to NINA users"),
                            ("permit", "Request access"),
                        ]
                    ),
                ),
                ("internal_ref", models.CharField(null=True)),
                ("external", models.BooleanField(default=False)),
                (
                    "service",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="resources",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectService",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "project",
                        "service",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="projects.project",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contributor",
            fields=[
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("maintainer", "Maintainer"), ("owner", "Owner")]
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "service",
                        "email",
                        "role",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="services.service",
                    ),
                ),
            ],
        ),
    ]
