# Generated by Django 5.2 on 2025-04-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_dmp_project_alter_project_status"),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="projects",
            field=models.ManyToManyField(
                blank=True, through="services.ProjectService", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="related",
            field=models.ManyToManyField(
                blank=True, through="services.ServiceRelated", to="services.service"
            ),
        ),
    ]
