# Generated by Django 5.2 on 2025-05-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_service_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="projects",
            field=models.ManyToManyField(
                blank=True,
                related_name="services",
                through="services.ProjectService",
                to="projects.project",
            ),
        ),
    ]
