# Generated by Django 5.2.11 on 2026-03-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_service_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resource",
            name="featured_icon",
            field=models.CharField(
                blank=True,
                help_text="Font Awesome icon class (e.g., 'fa-database', 'fa-server')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="featured_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
