# Generated by Django 6.0.4 on 2026-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_resource_featured_resource_featured_icon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="external",
            field=models.BooleanField(db_default=False, null=True),
        ),
        migrations.AlterField(
            model_name="resource",
            name="featured",
            field=models.BooleanField(db_default=False, null=True),
        ),
    ]
