# Generated by Django 5.1.6 on 2025-02-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="dmp",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProjectsConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dmp_survey_config",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projects Configuration",
            },
        ),
    ]
