# Generated by Django 5.2.9 on 2026-01-28 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="projectmembership",
            name="unique_user_per_project",
        ),
        migrations.AddField(
            model_name="projectmembership",
            name="protected",
            field=models.BooleanField(
                db_default=models.Value(output_field=models.BooleanField(), value=False)
            ),
        ),
        migrations.AlterField(
            model_name="projectmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Leader"),
                    ("manager", "Manager"),
                    ("data_manager", "Data Manager"),
                    ("member", "Member"),
                ],
                default="member",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("project", "user", "role"), name="unique_user_per_project"
            ),
        ),
    ]
