# Generated by Django 6.0.6 on 2026-10-01 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buckets", "0001_initial"),
        ("projects", "0002_remove_projectmembership_unique_user_per_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_storages",
                        to="projects.project",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_storages",
                        to="buckets.storage",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "storage"), name="unique_storage_per_project"
                    )
                ],
            },
        ),
    ]
