# Generated by Django 5.1.6 on 2025-03-21 10:25

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("projects", "0002_project_dmp_projectsconfiguration"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="core.GenericStringTaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
