# Generated by Django 5.1.6 on 2025-03-23 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_remove_project_dmp_dmp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dmp",
            name="project",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dmp",
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "Active"),
                    ("T", "Completed"),
                    ("P", "Parked"),
                    ("C", "Active"),
                ],
                null=True,
            ),
        ),
    ]
