# Generated by Django 5.2 on 2025-05-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_dmp_project_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "Active"),
                    ("T", "Completed"),
                    ("P", "Parked"),
                    ("C", "Not completed"),
                ],
                null=True,
            ),
        ),
    ]
