# Generated by Django 5.2 on 2025-05-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_project_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTopic",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="topics",
            field=models.ManyToManyField(blank=True, to="projects.projecttopic"),
        ),
    ]
