# Generated by Django 5.2 on 2025-09-10 21:00

from django.db import migrations, models

import dms.projects.models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0007_projecttopic_project_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmp",
            name="external_file",
            field=models.FileField(
                blank=True,
                help_text="Upload the external DMP",
                null=True,
                upload_to=dms.projects.models.upload_external_dmp,
            ),
        ),
        migrations.AddField(
            model_name="dmp",
            name="external_reference",
            field=models.CharField(
                blank=True, help_text="URL or reference to an external DMP", null=True
            ),
        ),
    ]
