# Generated by Django 5.2 on 2025-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0008_dmp_external_file_dmp_external_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmp",
            name="featured_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
