# Generated by Django 5.2 on 2025-12-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_alter_project_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="dmp",
            name="schema",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
