# Generated by Django 6.0.6 on 2026-10-01 07:41

from django.db import migrations, models

import buckets.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "endpoint_url",
                    models.CharField(
                        blank=True,
                        help_text="Custom S3-compatible endpoint URL (e.g. MinIO/RustFS). Leave blank to use real AWS S3.",
                        max_length=255,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=64)),
                ("bucket_name", models.CharField(max_length=255)),
                ("access_key_id", buckets.fields.EncryptedCharField(max_length=512)),
                (
                    "secret_access_key",
                    buckets.fields.EncryptedCharField(max_length=512),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Template string rendered against caller-supplied context, e.g. '{project_id}/{dataset_id}'. Not validated.",
                        max_length=255,
                    ),
                ),
                (
                    "canned_acl",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("public-read", "Public read"),
                            ("public-read-write", "Public read/write"),
                            ("authenticated-read", "Authenticated read"),
                            ("aws-exec-read", "AWS exec read"),
                            ("bucket-owner-read", "Bucket owner read"),
                            ("bucket-owner-full-control", "Bucket owner full control"),
                        ],
                        default="private",
                        max_length=32,
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="Available to every project, regardless of explicit assignment.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage",
                "verbose_name_plural": "Storages",
            },
        ),
    ]
